// Generates public/sitemap.xml at build time.
// Run automatically before `vite build` via the npm `prebuild` hook.
//
// MAINTENANCE: if brands are added/removed/renamed in
// src/data/en/brands.ts, update BRAND_SLUGS below.
// (Kept inline to avoid adding a TS loader to devDependencies.)

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const OUT = resolve(ROOT, "public", "sitemap.xml");

const SITE_URL = "https://raylabgroup.com";

const BRAND_SLUGS = [
  "cairo-scan",
  "technoscan",
  "crc",
  "medray",
  "cairo-scan-polyclinics",
  "technoscan-polyclinics",
  "specialized-clinics",
  "ray-medical",
];

const STATIC_ROUTES = [
  { path: "/", changefreq: "weekly", priority: "1.0" },
  { path: "/about", changefreq: "monthly", priority: "0.8" },
  { path: "/services", changefreq: "monthly", priority: "0.8" },
  { path: "/network", changefreq: "monthly", priority: "0.8" },
  { path: "/platforms", changefreq: "monthly", priority: "0.8" },
  { path: "/investors", changefreq: "monthly", priority: "0.8" },
  { path: "/contact", changefreq: "monthly", priority: "0.6" },
  { path: "/directory", changefreq: "monthly", priority: "0.6" },
  { path: "/gallery", changefreq: "monthly", priority: "0.6" },
  { path: "/privacy", changefreq: "yearly", priority: "0.3" },
  { path: "/terms", changefreq: "yearly", priority: "0.3" },
];

const today = new Date().toISOString().slice(0, 10);

const allRoutes = [
  ...STATIC_ROUTES,
  ...BRAND_SLUGS.map((slug) => ({
    path: `/platforms/${slug}`,
    changefreq: "monthly",
    priority: "0.9",
  })),
];

const urlEntries = allRoutes
  .map(
    ({ path, changefreq, priority }) =>
      `  <url>\n    <loc>${SITE_URL}${path}</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>${changefreq}</changefreq>\n    <priority>${priority}</priority>\n  </url>`,
  )
  .join("\n");

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand.
     Regenerate with: npm run build (or node scripts/generate-sitemap.mjs) -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlEntries}
</urlset>
`;

writeFileSync(OUT, xml, "utf8");

console.log(`[sitemap] wrote ${allRoutes.length} URLs to ${OUT} (lastmod=${today})`);
