/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlatformsRouteImport } from './routes/platforms'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformsSlugRouteImport } from './routes/platforms.$slug'

const PlatformsRoute = PlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformsSlugRoute = PlatformsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PlatformsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/platforms': typeof PlatformsRouteWithChildren
  '/platforms/$slug': typeof PlatformsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/platforms': typeof PlatformsRouteWithChildren
  '/platforms/$slug': typeof PlatformsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/platforms': typeof PlatformsRouteWithChildren
  '/platforms/$slug': typeof PlatformsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/platforms' | '/platforms/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/platforms' | '/platforms/$slug'
  id: '__root__' | '/' | '/about' | '/platforms' | '/platforms/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PlatformsRoute: typeof PlatformsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/platforms': {
      id: '/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof PlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platforms/$slug': {
      id: '/platforms/$slug'
      path: '/$slug'
      fullPath: '/platforms/$slug'
      preLoaderRoute: typeof PlatformsSlugRouteImport
      parentRoute: typeof PlatformsRoute
    }
  }
}

interface PlatformsRouteChildren {
  PlatformsSlugRoute: typeof PlatformsSlugRoute
}

const PlatformsRouteChildren: PlatformsRouteChildren = {
  PlatformsSlugRoute: PlatformsSlugRoute,
}

const PlatformsRouteWithChildren = PlatformsRoute._addFileChildren(
  PlatformsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PlatformsRoute: PlatformsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
